services:
  application:
    build: .
    image: application
    container_name: application
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=all
    volumes:
      - .:/workspace
  dotfiles:
    image: key5n/dotfiles:python3.6.15
    volumes:
      - .:/workspace
